### ISSUE TITLE
Staging build deploys static assets to live S3

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/polling_deploy#6]
At the moment, whenever we run a build, the static assets are deployed to our live S3 instance, even if we're only building a staging server. If we deploy a build with any sort of meaningful JS/CSS changes (e.g: updating the theme), this has the potential to break the live instance.

We should add the ability to deal with this cleanly.

**Comment by chris48s** [comment]
2 approaches:

* Have one S3 bucket for prod and one for staging
* Use one bucket and rely on fingerprinting to deal with this for us

**Comment by ashb** [comment]
Approach no.2 has other benenfits too (such as assets can be set with an expiry time far in the future.) but the first approach might be quicker.

**Comment by chris48s** [comment]
Closed in #78
